### ISSUE TITLE
[FeatureReq]Support real client IP retrieval when using FRP reverse proxy

### ISSUE THREAD

**Issue by txsiny** [NikitaCartes/EasyAuth#222]
**Is your feature request related to a problem? Please describe.**
I'm running a Fabric-based Minecraft server on my local computer, which doesn't have a public IP. To expose it to the internet, I use [FRP](https://github.com/fatedier/frp), which establishes a reverse TCP tunnel from my local machine to a cloud VPS.

However, when I installed the EasyAuth mod, I noticed that all incoming connections appear to come from 127.0.0.1. As a result, EasyAuth treats every player as coming from the same IP address, and anyone can log in without a password, bypassing authentication entirely.

According to the [FRP documentation](https://github.com/fatedier/frp/blob/dev/README.md#get-real-ip), it supports sending the real client IP to the backend server via the Proxy Protocol (v2).

**Describe the solution you'd like**
I'd like to request that EasyAuth support retrieving the real client IP address when the server is being accessed through FRP using Proxy Protocol.

**Describe alternatives you've considered**

**Additional context**

**Comment by Lyrth** [comment]
Putting it here in case anyone sees this:

https://www.curseforge.com/minecraft/mc-mods/proxy-protocol-support seems to work perfectly fine together with EasyAuth.

**Comment by MatchaKopiCodes** [comment]
Hi, piggybacking onto this issue, I have a minecraft server using itzg's container. The standard docker compose file used Bridge/NAT networking by default and all Client IP addresses seem to come from one IP, allowing griefers to spoof usernames and access without login up to 1 hour after the real player logged out. 

Just an oversight on my part, but I believe its common enough mistake that there should at least be a warning about setting session by IP if the server is behind a proxy or virtual networks like docker. 

Might be even better, although less convenient to disable sessions by default. 

In case anyone stumbled onto the same issue, here's how I fixed mine by setting network_mode to host, and removing the Port Bridging. 

Note that I have no experience with other kinds of network topology. So if your router is also configured differently, it might also hide real client IPs even with this fix, so check the logs of player logins to ensure they have different IPs. 

```yml
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: minecraft_fabric_main
    tty: true
    stdin_open: true
    restart: always
    network_mode: "host" # <<<< Extremely important

#  ports:
#   - "25565:25565"  <<<< Do not use, set server port number by environment variable. 

    environment: 
...
```
